language: ruby

rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3

sudo: false

services: mongodb

before_script:
  - mysql -e 'CREATE DATABASE statesman_test;'
  - psql -c 'CREATE DATABASE statesman_test;' -U postgres

script:
  - bundle exec rubocop
  - bundle exec rake

env:
  - "RAILS_VERSION=3.2.21"
  - "RAILS_VERSION=4.0.12"
  - "RAILS_VERSION=4.1.8"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=4.2.0 DATABASE_URL=mysql2://root@localhost/statesman_test"
  - "RAILS_VERSION=4.2.0 DATABASE_URL=postgres://postgres@localhost/statesman_test"
